// Tokens para inyección de dependencias
export const PERSONA_REPOSITORY = 'PERSONA_REPOSITORY';
export const CONTACTO_REPOSITORY = 'CONTACTO_REPOSITORY';
export const SERVICIO_SISTEMA_EXTERNO = 'SERVICIO_SISTEMA_EXTERNO';
export const SERVICIO_NOTIFICACION = 'SERVICIO_NOTIFICACION';
